<script>
	$(document).ready(function(){
			$(".c1").click(function(){
   				$(".c1").addClass("selected");
   				$(".c2").removeClass("selected");
   				$(".c3").removeClass("selected");
   				$(".c4").removeClass("selected");
   				$(".c5").removeClass("selected");
   				$(".c6").removeClass("selected");
   				$(".c7").removeClass("selected");
   				$(".c8").removeClass("selected");
				});
				$(".c2").click(function(){
   				$(".c2").addClass("selected");
   				$(".c1").removeClass("selected");
   				$(".c3").removeClass("selected");
   				$(".c4").removeClass("selected");
   				$(".c5").removeClass("selected");
   				$(".c6").removeClass("selected");
   				$(".c7").removeClass("selected");
   				$(".c8").removeClass("selected");
				});
        $(".c3").click(function(){
          $(".c3").addClass("selected");
          $(".c1").removeClass("selected");
          $(".c2").removeClass("selected");
          $(".c4").removeClass("selected");
          $(".c5").removeClass("selected");
          $(".c6").removeClass("selected");
          $(".c7").removeClass("selected");
          $(".c8").removeClass("selected");
        });
          $(".c4").click(function(){
          $(".c4").addClass("selected");
          $(".c1").removeClass("selected");
          $(".c2").removeClass("selected");
          $(".c3").removeClass("selected");
          $(".c5").removeClass("selected");
          $(".c6").removeClass("selected");
          $(".c7").removeClass("selected");
          $(".c8").removeClass("selected");
        });
          $(".c5").click(function(){
          $(".c5").addClass("selected");
          $(".c1").removeClass("selected");
          $(".c2").removeClass("selected");
          $(".c3").removeClass("selected");
          $(".c4").removeClass("selected");
          $(".c6").removeClass("selected");
          $(".c7").removeClass("selected");
          $(".c8").removeClass("selected");
        });
          $(".c6").click(function(){
          $(".c6").addClass("selected");
          $(".c1").removeClass("selected");
          $(".c2").removeClass("selected");
          $(".c3").removeClass("selected");
          $(".c4").removeClass("selected");
          $(".c5").removeClass("selected");
          $(".c7").removeClass("selected");
          $(".c8").removeClass("selected");
        });
          $(".c7").click(function(){
          $(".c7").addClass("selected");
          $(".c1").removeClass("selected");
          $(".c2").removeClass("selected");
          $(".c3").removeClass("selected");
          $(".c4").removeClass("selected");
          $(".c5").removeClass("selected");
          $(".c6").removeClass("selected");
          $(".c8").removeClass("selected");
        });
          $(".c8").click(function(){
          $(".c8").addClass("selected");
          $(".c1").removeClass("selected");
          $(".c2").removeClass("selected");
          $(".c3").removeClass("selected");
          $(".c4").removeClass("selected");
          $(".c5").removeClass("selected");
          $(".c6").removeClass("selected");
          $(".c7").removeClass("selected");
        });
	});
</script>